### ISSUE TITLE
Todo: add more build targets such that releases can be produced better

### ISSUE THREAD

**Issue by V-Karch** [V-Karch/hshopper#6]
- [x] x86_64-pc-windows-gnu
- [x] x86_64-pc-windows-msvc
- [ ] x86_64-apple-darwin
- [ ] aarch64-apple-darwin
